version: '3.6'
services:
  database:
    image: mongo
    container_name: 'database'
    command: [--auth]
    restart: 'always'
    ports: 
      - '27017:27017'
    volumes: 
      - 'mongodata:/data/db'
  api:
    container_name: 'api'
    restart: 'always'
    build:
      context: .
    env_file: 
      - .env
    ports:
      - "8080:8080"
    volumes:
      - "./config:/api/config:ro"
      - "./services:/api/services:ro"
      - "./utils:/api/utils:ro"
      - "./models:/api/models:ro"
    depends_on: 
      - database
    networks:
      - backend
  nginx:
    image: nginx:1.13
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - backend
  certbot:
    image: certbot/certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes: 
  mongodata:
networks: 
  backend:

